### ISSUE TITLE
Symfony console dependency version

### ISSUE THREAD

**Issue by PatrickBauer** [AydinHassan/progress-bar-log#1]
Why is ^3.2 the version contraint for the symfony console? 

As far as I can see, the ProgressBarLog only uses some base functions like start() and advance(). Right now its not usable inside Drupal8 projects which are currently locked to v2.8.17 (using the Drupal console).

**Comment by AydinHassan** [comment]
@PatrickBauer no reason - I just pulled in latest version. Feel free to send a PR to loosen it :)

**Comment by AydinHassan** [comment]
fixed in 6ff229495c3edf2b083b017e680d0c964b56956a
