### ISSUE TITLE
[Feature-request] Don't clear the whole screen

### ISSUE THREAD

**Issue by PatrickBauer** [AydinHassan/progress-bar-log#2]
As I can see you're using 2J as an ASCII Escape command to clear the whole window. 
I'd like to see a version where only the number of lines is cleared which are used.

It could calculate in this way: height of the progress bar + number of current log messages.
The height of the progress bar is calculated by the progress bar itself in its clear() method.

Maybe you could concatenate it. Using $this->clear() which clears all log lines and then calling $this->progressBar->clear() to clear the bar itself.

**Comment by AydinHassan** [comment]
Sounds fair. I'm not sure how soon i'll get around to this. Again, feel free to send a PR if you have more time than me :)

**Comment by AydinHassan** [comment]
I found some time and created a PR - would you mind taking a look? #3

**Comment by PatrickBauer** [comment]
Looks good to me, thanks for the features! :)

**Comment by AydinHassan** [comment]
np - I've tagged `1.1.0` !
